### ISSUE TITLE
Python 3.3 compatibility

### ISSUE THREAD

**Issue by sebastinas** [general03/flask-autoindex#13]
Now that flask finally supports Python 3.3, I tried to build and test flask-autoindex with Python 3.3. flask-silk seems to work without problems, but the test suite of flask-autoindex fails with:

```
% python3 setup.py test
running test
running egg_info
writing Flask_AutoIndex.egg-info/PKG-INFO
writing requirements to Flask_AutoIndex.egg-info/requires.txt
writing dependency_links to Flask_AutoIndex.egg-info/dependency_links.txt
writing top-level names to Flask_AutoIndex.egg-info/top_level.txt
reading manifest file 'Flask_AutoIndex.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Flask_AutoIndex.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "/usr/lib/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.3/distutils/dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 138, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 118, in with_project_on_sys_path
    func()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 164, in run_tests
    testLoader = cks
  File "/usr/lib/python3.3/unittest/main.py", line 124, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.3/unittest/main.py", line 168, in parseArgs
    self.createTests()
  File "/usr/lib/python3.3/unittest/main.py", line 175, in createTests
    self.module)
  File "/usr/lib/python3.3/unittest/loader.py", line 137, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.3/unittest/loader.py", line 137, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.3/unittest/loader.py", line 122, in loadTestsFromName
    test = obj()
  File "setup.py", line 25, in run_tests
    from tests import suite
  File "/home/sebastian/development/flask-autoindex/tests/__init__.py", line 5, in <module>
    from flask.ext.autoindex import *
  File "/usr/lib/python3/dist-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/home/sebastian/development/flask-autoindex/flask_autoindex/__init__.py", line 16, in <module>
    from .entry import *
  File "/home/sebastian/development/flask-autoindex/flask_autoindex/entry.py", line 3, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'
```

It would be great if this could be fixed and flask-autoindex be ported to Python 3.3.

**Comment by akgun** [comment]
Open **venv\Lib\site-packages\flask_autoindex\entry.py** file.
Replace **from urlparse import urljoin** with **from urllib.parse import urljoin**. And find **explore** method in **Directory** class. Comment out **entries = sorted(entries, key=compare)** line.

This works on Windows 8.

**Comment by BrianLusina** [comment]
@akgun Thank you for the tip. Really helped.

**Comment by hugovk** [comment]
This issue can be closed now, Python 3.3 reaches end of life this month.

https://en.wikipedia.org/wiki/CPython#Version_history

**Comment by fnkr** [comment]
@hugovk This isn't about Python 3.3, it's about switching from Python 2 to 3 (or supporting both). At least that was the reason I +1'ed this three years ago.

**Comment by hugovk** [comment]
Okay, carry on! :)

Looks like @akgun's suggestion could be turned into a PR.

**Comment by general03** [comment]
The python 3.3 is not supported yet by the projet
